name: Compile Ubuntu

on:
  - push
  - pull_request

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create latest --target master
  build:
    runs-on: ${{ matrix.os }}

    if: always()
    needs: [release]

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-latest]

    env:
      BUILD_DIR: build
      DEBIAN_FRONTEND: noninteractive

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libncurses5-dev libncursesw5-dev libdrm-dev libsystemd-dev

    - name: Configure CMake
      run: cmake -S . -B $BUILD_DIR

    - name: Build
      run: cmake --build $BUILD_DIR

    - name: Install
      run: DESTDIR="$PWD/build/install" cmake --build $BUILD_DIR --target install
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: nvtop ${{ matrix.os }}
        path: ${{ env.BUILD_DIR }}/install

    - name: Upload to release
      if: steps.release.outcome == 'success'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        mv "$PWD/build/install/usr/local/bin/nvtop" nvtop-${{matrix.os}}
        gh release upload latest nvtop-${{matrix.os}} --clobber 
